### ISSUE TITLE
Implement `google/supl-client`. Being worked on branch supl.

### ISSUE THREAD

**Issue by marticliment** [griush/GalileoHack#24]

**Comment by griush** [comment]
There's doc-comments inside the supl-client source code so we could run some doc generator or directly read from source.

**Comment by griush** [comment]
found this also:
[https://github.com/google/supl-client/pull/7](https://github.com/google/supl-client/pull/7)

**Comment by griush** [comment]
Example here:
[GalileoFront/app/src/main/java/com/google/location/custom_suplclient/supl/SuplTester.java](https://github.com/griush/GalileoHack/blob/supl/GalileoFront/app/src/main/java/com/google/location/custom_suplclient/supl/SuplTester.java)
