### ISSUE TITLE
GNSS data log page

### ISSUE THREAD

**Issue by griush** [griush/GalileoHack#31]
Make another page that would display the raw data recieved as if it was a console.
Open here for discussion...

**Comment by arf20** [comment]
Can we print NMEA messages on a 'terminal'?

**Comment by griush** [comment]
la idea es usar el getData callback y cada vez que se recibe un mensaje de 40 bits de un satelite, poner la id y los 40 bits (en hexa mejor) y simular que sale por una terminal, en plan, poner tipica fuente mono y eso.
https://github.com/griush/GalileoHack/blob/master/GalileoFront/app/src/main/java/com/gnsstracker/mainapp/SatelliteDataHandler.java#L307

**Comment by griush** [comment]
#48
